### ISSUE TITLE
Having trouble building cpp-ethereum.xcodeproj in XCode

### ISSUE THREAD

**Issue by anitamengzhuolu** [ethereum/aleth#3407]
I saw these errors when building with "xcodebuild" in terminal:

/usr/local/include/boost/random/discrete_distribution.hpp:95:60: error: unused
      parameter 'average' [-Werror,-Wunused-parameter]
    static WeightType normalize(WeightType val, WeightType average)
                                                           ^
/usr/local/include/boost/random/discrete_distribution.hpp:186:66: error: unused
      parameter 'weights' [-Werror,-Wunused-parameter]
    static WeightType try_get_sum(const std::vector<WeightType>& weights)
                                                                 ^
2 errors generated.

Do anyone know what's going on? Thanks in advance!

**Comment by chriseth** [comment]
Thanks for the report! Can you tell us which version of xcode, boost and clang you are using and on which operating system?

**Comment by bnrmaster** [comment]
@chriseth 
I met the same problem with @anitamengzhuolu 
my operating system is macOS Sierra 10.12.1
**Xcode version:**8
**Apple LLVM version** 8.0.0 (clang-800.0.42.1)
**boost version** 1.62.0.
Target: x86_64-apple-darwin16.1.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

After I modified the discrete_distribution.hpp and "avoid" the errors
I met more errors as below:
/usr/local/include/boost/test/tools/old/impl.hpp:107:17: Comparison of integers of different signs: 'const int' and 'const unsigned long'
/usr/local/include/boost/test/tools/old/impl.hpp:107:17: Comparison of integers of different signs: 'const unsigned long' and 'const int'


I guess the problem is the boost is not adapt the new system?

**Comment by chriseth** [comment]
It looks like the boost library does not compile under apple llvm 8.0.0, yes.

**Comment by bnrmaster** [comment]
@chriseth 
I used "$brew Install boost" command to install the boost ,should I do something else to solve the problem?
Or how to compile the boost library under apple llvm 8.0.0?
Could anyone give me some advise?

**Comment by halfalicious** [comment]
Please reactivate if you still hit this
