### ISSUE TITLE
--mode peer is broken

### ISSUE THREAD

**Issue by gumb0** [ethereum/aleth#4703]
Starting with `--mode peer` leads to uncaught exception.
```
> eth/eth --mode peer
cpp-ethereum, a C++ Ethereum client
cpp-ethereum 1.3.0
  By cpp-ethereum contributors, (c) 2013-2016.
  See the README for contributors and credits.
  ℹ  01:52:56 PM.317|p2p  UPnP device not found.
Node ID: enode://493d52068ec72230688da539926f47a452b762bc348d2ab1491f399b532186d71d7c512e09ffb8e9c24d292d064c00f6234ef1221bc0d86093d2de32358d33da@0.0.0.0:0
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<dev::InterfaceNotSupported>'
  what():  std::exception
fish: Job 1, “eth/eth --mode peer” terminated by signal SIGABRT (Abort)
```

I'm not sure why this mode existed and probably we should just remove it.

**Comment by chfast** [comment]
Inspect and remove if you can't find anything there.

**Comment by gumb0** [comment]
It was supposed to run a node without any capabilities (no eth, no whisper)
Maybe it's something like a bootnode of geth - not acting as a full client, but participating in node discovery?

**Comment by chfast** [comment]
We will be setting up a testnet for eWASM today, so I will try it.

**Comment by gumb0** [comment]
The fix could be for aleth's `main` function just to skip anything accessing `web3.ethereum()` in this mode.

Or better we could make a separate executable for it, which would have only networking CLI options (in go-ethereum there's a separate binary for the bootnode)

**Comment by halfalicious** [comment]
Information on geth's bootnode executable: https://github.com/ethereum/go-ethereum/wiki/Setting-up-private-network-or-local-cluster

**Comment by halfalicious** [comment]
I've looked at the Aleth networking code (`Hosts` and `NodeTable`) and the Geth bootnode documentation and here's how I'm planning on addressing this issue:
* I'm going to create a new executable (called something like `bootnode`) which will listen on a specific UDP port for discovery requests. This port will be configurable via a command-line argument.
* This new bootnode mode will only be relevant if you want to run a private chain (since all it does is build a node table via discovery requests and then service discovery "find neighbor" requests using this table...it will not connect to the Ethereum bootnodes defined in `Host::PoCHosts` or any hosts supplied via the command line, which appears to be the same behavior as Geth's bootnode executable)
* Here are the Aleth command-line arguments that I'll be implementing in this new executable:

```
  --public-ip <ip>                Force advertised public IP to the given IP (default: auto)
  --listen-ip <ip>(:<port>)       Listen on the given IP for incoming connections (default: 0.0.0.0)
  --listen <port>                 Listen on the given port for incoming connections (default: 30303)
```
  
I'm also going to add an argument which enables one to supply information so that Aleth will use the same enode URL for the bootnode on each launch...note that it looks like Aleth currently generates a new enode URL on every launch. For example (note the varying values in the "Id:" field):
```

C:\Users\nilse\Documents\Code\aleth\build\aleth\Debug>aleth --ropsten
aleth, a C++ Ethereum client
INFO  11-25 18:22:18 main net    Id: ##e8694d7dGÇª
^C
C:\Users\nilse\Documents\Code\aleth\build\aleth\Debug>aleth --ropsten
aleth, a C++ Ethereum client
INFO  11-25 18:22:22 main net    Id: ##d8572970GÇª
^C
C:\Users\nilse\Documents\Code\aleth\build\aleth\Debug>aleth --ropsten
aleth, a C++ Ethereum client
INFO  11-25 18:22:23 main net    Id: ##3cf8732bGÇª
^C
```

Additionally, I'm going to remove the `--mode` option from Aleth since it doesn't actually do anything and the functionality that it was meant to provide will be provided via this new executable.

**Comment by chfast** [comment]
I think it should connect to "PoCHosts" in some cases (e.g. when running as a Ethereum public bootnode).

Are you sure the code duplication with aleth.exe will not be too big? In the end both tools will support the same options.

Name it `aleth-bootnode`.

**Comment by gumb0** [comment]
> Since the discovery logic is implemented in NodeTable (Host::m_net), I'll add a constructor parameter to WebThreeDirect::WebThreeDirect which will indicate whether or not the WebThreeDirect instance should only perform discovery functionality (e.g. bool discoveryOnly). 

Maybe we don't need `WebThreeDirect` class for bootnode at all, try just creating `p2p::Host` directly, it should be simple. Maybe even `NodeTable` is all we need.

**Comment by gumb0** [comment]
> I'm also going to add an argument which enables one to supply information so that Aleth will use the same enode URL for the bootnode on each launch...note that it looks like Aleth currently generates a new enode URL on every launch.

This is a bug on Windows!
It is supposed to save the enode address to `network.rlp` file (together with NodeTable contents) when application exits, and restore it on next start.

https://github.com/ethereum/aleth/blob/064b04d27a6637252ece880ef81c7381e46efc79/aleth/main.cpp#L1142-L1144

It works fine for me on Linux, but on Windows the exit happens somewhat differently, so the code in the end of `main` function is not executed when you hit Ctrl-C.

Would be great to properly fix it, but I don't know how.

**Comment by chfast** [comment]
Handling Ctrl-C is tricky and requires proper main function layout + some OS-specific code.

**Comment by halfalicious** [comment]
> 
> 
> > I'm also going to add an argument which enables one to supply information so that Aleth will use the same enode URL for the bootnode on each launch...note that it looks like Aleth currently generates a new enode URL on every launch.
> 
> This is a bug on Windows!
> It is supposed to save the enode address to `network.rlp` file (together with NodeTable contents) when application exits, and restore it on next start.
> 
> [aleth/aleth/main.cpp](https://github.com/ethereum/aleth/blob/064b04d27a6637252ece880ef81c7381e46efc79/aleth/main.cpp#L1142-L1144)
> 
> Lines 1142 to 1144 in [064b04d](/ethereum/aleth/commit/064b04d27a6637252ece880ef81c7381e46efc79)
>  auto netData = web3.saveNetwork(); 
>  if (!netData.empty()) 
>      writeFile(getDataDir() / fs::path("network.rlp"), netData); 
> 
> It works fine for me on Linux, but on Windows the exit happens somewhat differently, so the code in the end of `main` function is not executed when you hit Ctrl-C.
> 
> Would be great to properly fix it, but I don't know how.

Thanks for the tip 😃 We appear to setup a signal handler at the end of main which should enable graceful termination on Windows: https://github.com/ethereum/aleth/blob/030ad9ca2e5b41043554096af7a10216a9fb2fe9/aleth/main.cpp#L1122-L1124

I think that at one point Windows might have supported the signals we register the handler for (https://msdn.microsoft.com/en-us/library/ms811896.aspx#ucmgch09_topic3) ...I'll take a closer look to see why this isn't working. It might be that we need to have a Windows-specific handler that we register with something like [SetConsoleCtrlHandler](https://docs.microsoft.com/en-us/windows/console/setconsolectrlhandler). 

> 
> 
> I think it should connect to "PoCHosts" in some cases (e.g. when running as a Ethereum public bootnode).

I don't think that Geth's bootnode does this, it appears to just listen on a UDP port. Thinking about what a bootnode could be useful for, I think that Geth's approach makes sense...I don't see the value of running a boot node on a public chain, though I'd love to get your thoughts on this since there might be valid scenarios where this provides value that I'm not thinking of. 

> 
> Are you sure the code duplication with aleth.exe will not be too big? In the end both tools will support the same options.

I think that if we're just moving over a few network options (e.g. `--public-ip`, `--listen-ip`, and `--listen`) then the code duplication won't be too bad since I can just move the processing of these args into a separate file similar to how log arguments are processed (see libdevcore\LoggingProgramOptions.h), though I'll know for sure once I start digging into the code. However, if we want to keep most of the args (i.e. we want to enable the bootnode binary to do more than just listen on a UDP port) then I think that code duplication will be a problem.

> 
> Name it `aleth-bootnode`.
👍

**Comment by gumb0** [comment]
> @gumb0 : I think it might be better to create NodeTable separately without going through the WebThreeDirect and Host classes...this is because otherwise I'll need to modify both WebThreeDirect and Host to just support creating a NodeTable instance without starting any other functionality (e.g. no p2p). This could add some clutter, particularly to Host. What do you think?

So my efforts lately were directed to make the interface of libp2p smaller and simpler, with the potential goal of shipping it as a separate library. Therefore I'd like to have a `Host` class only the entry point to the library and `NodeTable` to be hidden.

Wouldn't just passing empty `_interfaces` to `WebThreeDirect` be enough? At least I think that was the idea originally - when no interfaces enabled, only discovery is being run.

And as I mentioned I think it'd be even simlpler not to use `WebThreeDirect` and just instantiate `p2p::Host`. Then if no `registerCapability` is called, there're no capabilities and only Discovery is being run.
I think we should try this scenario; if it doesn't work, hopefully it's not difficult to fix.

> On a related note, I'm also going to add a new mode to Aleth which enables one to supply a list of boot nodes to use for p2p discovery bootstrapping, similar to geth's --bootnodes argument:
--bootnodes value Comma separated enode URLs for P2P discovery bootstrap (set v4+v5 instead for light servers)

Not sure about this, seems like a not really necessary complication of the CLI. Does a user really care which kind of node this is? I'd say it's more convenient to provide one list of peers, like we do now.

**Comment by halfalicious** [comment]
Closing since `aleth-bootnode` now provides the functionality intended to be provided via `--mode peer` and consequently the `--mode` argument has been removed from aleth
