### ISSUE TITLE
In-memory database implementation

### ISSUE THREAD

**Issue by gumb0** [ethereum/aleth#5262]
This issue is the continuation of https://github.com/ethereum/aleth/issues/4669 and describes one point from it:

>  Implement MemoryDB as a simple wrapper of std::unordered_map.

`OverlayDB` refactoring can be done as a separate task later. Until then we need to rename currently existing `MemoryDB`

- [x] Rename `MemoryDB`, I suggest the name `StateMemoryDB`

- [x] Implement `DatabaseFace` using `std::unordered_map` as backend key/value storage. This will be the new `MemoryDB`

- [x] Allow selection of either `MemoryDB` or `LevelDB` at run-time (Currently DB implementation is selected at compile time via `DBImpl` alias) I think it can be done in the fashion simiar to how VM implementation is created currently, see `setVMKind()` / `VMFactory::create()` 
Make sure the DB factory is used in `BlockChain` and when creating state DB (`OverlayDB`)

- [x] Add aleth command line parameter to enable `MemoryDB` (maybe `--memory-db`). We could create something similar to `vmProgramOptions()` for this.
(But I'd say we don't need to list all supported DB engines in CLI, so DB program options would include just `--db-path` and `--memory-db` (mutually exclusive))

cc @chfast

**Comment by chfast** [comment]
I don't get why `StateMemoryDB`, but I have not seen its implementation.

For CLI I prefer having common prefix for groups. It could be something like this:

1. `--db-path` and `--db-in-memory`.
2. `--db-path=memory`.
3. `--db={leveldb, memory}` and `--db-path` acceptable only for memory kind.
4. `--db=leveldb://path`, `--db=memory`.

**Comment by gumb0** [comment]
> I don't get why `StateMemoryDB`, but I have not seen its implementation.

This class is confusingly used as both a cache when accessing State DB and as in-memory DB (at least in some tests, this is the part we want to replace with new `MemoryDB` later).
So it's kind of neither exactly cache nor exactly DB and so coming up with great name is difficult. Anyway I hope this would a temporary thing and we'll refactor it out.

For CLI I think I like option 1.

**Comment by chfast** [comment]
How about StateCacheDB?

**Comment by gumb0** [comment]
Fine with me.

**Comment by halfalicious** [comment]
I've renamed `MemoryDB `to `StateCacheDB `(both the source files and the classes themselves) and updated the relevant source, test, and documentation references. I also have an initial thread-safe implementation of a `std::unordered_map`-backed new `MemoryDB`. Following up on something we chatted about via mail - I think that we need to use `std::unordered_map` as storage in `MemoryDBWriteBatch` (rather than `std::vector`) since the class has a kill function and using a vector means we'll need to do a linear search. I'm unfortunately still wrangling with build issues so I haven't compiled the code yet but it's pretty straightforward so I don't think there will be many issues. I'll follow up on the build issues via email. 

Also, a question - does `MemoryDBWriteBatch` need to be thread-safe?

Tomorrow I'll start looking into enabling DB selection at runtime and if I get around to it, updating the command-line parameters / documentation.

**Comment by gumb0** [comment]
Oh right, I forogot about `WriteBatchFace::kill()`, `unordered_map` is fine then.

Write batch can be not thread-safe, because it's not thread-safe in both LevelDB and RocksDB API, and we certainly use it from the single thread only

**Comment by halfalicious** [comment]
I've looked into making the database selectable at runtime and have a question - just to confirm, I should only use the new `MemoryDB` to store the state i.e. I should create an instance of it in `State::openDB` using the new `DBFactory `that I'll be creating: https://github.com/ethereum/aleth/blob/3f5a26f65afd6bb7a71090523fe872191341a89f/libethereum/State.cpp#L75-L80

I'm planning on having the `DBFactory::create` function take the file path and in the case of `MemoryDB`, just discard it.

**Comment by gumb0** [comment]
1. The same is needed for two databases in `BlockChain` class https://github.com/ethereum/aleth/blob/3f5a26f65afd6bb7a71090523fe872191341a89f/libethereum/BlockChain.cpp#L244-L245

2. Yes, and actually all the tests that use `TransientDirectory` should better use in-memory database. But that can go into a separate PR.

**Comment by halfalicious** [comment]
I think that we're going to need to make some changes surrounding the `--db-path` parameter as a part of this issue. It looks like the path that the user can supply at runtime via this parameter is used both as the root path when building paths for storing database data (e.g. blocks, state, configuration data) as well as non-database data (e.g. config.rlp, network.rlp, keystore files, etc). 

Since a database path parameter doesn't make sense when a memory database is in use but we should still enable the user to choose a non-default path for storing non-database data e.g. keystore and config files, I think we should repurpose the `--db-path` parameter for just the database path and add another parameter (I'm thinking something like `--data-dir`) for the other files. Thoughts?

I'm also planning on adding a bit of special casing around file system operations related to the databases so that they're skipped if a memory database is in use. For example, the `fs` and `writeFile` calls below:

https://github.com/ethereum/aleth/blob/700e944b4f9f0fdc8174f5e95ef60cfa2536eb22/libethereum/BlockChain.cpp#L226-L234

**Comment by gumb0** [comment]
Adding `--data-dir` parameter seems ok to me. By default it should be equal to `--db-path` given.
(Maybe ideally in use cases where we need in-memory DB we should have keys & configs also in memory only, but this might be too big of a change, I think it's fine to keep them on disk now)

Yeah file system operations should be skipped somehow. This particular snippet I think is not useful at all right now (we don't have different versions of DB around), but there are others that we need to keep (like deleting DB files when `--kill` is requested).


Anyway it's better create a smaller PR with the parts you already have completed, if you got them compiling (or even if not)

**Comment by halfalicious** [comment]
I took a quick look at where file system operations are invoked and I think that we'll only need to skip some of the operations in Blockchain and State. The rest of the operations (related to things like snapshots, the keystore, and configuration files) we can leave alone and perhaps move them to in-memory in a future change.
