### ISSUE TITLE
Aleth bootnode improvements

### ISSUE THREAD

**Issue by chfast** [ethereum/aleth#5391]
- [x] Does the bootnode need to open the TCP port?
- [ ] It runs with very low resources, but the memory usage is growing slightly over time. Check if we don't keep some data forever (like pending peers, evictions).
- [x] When running devp2p without any capabilities the Hello messages should be ignored.

**Comment by halfalicious** [comment]
Regarding this:

> 
>     * [ ]  Does the bootnode need to open the TCP port?
> 

From what I understand discovery (i.e. no peer connections) only uses UDP - the [Node Discovery v4 page](https://github.com/ethereum/devp2p/blob/master/discv4.md)'s **Wire Protocol** section explicitly mentions that the discovery packets are UDP datagrams:

> Node discovery messages are sent as UDP datagrams. The maximum size of any packet is 1280 bytes.

Consequently I don't think we need to open a TCP port.

**Comment by halfalicious** [comment]
Looked at the network code in Host, we don't need to start the TCP listener (`m_tcp4Acceptor`) since we don't need to support p2p connections at all, we just need to receive discovery packets (which is handled via UDP sockets in `NodeTable`). I'll take a closer look at how to avoid starting the TCP listener.

**Comment by halfalicious** [comment]
> 
> 
> Looked at the network code in Host, we don't need to start the TCP listener (`m_tcp4Acceptor`) since we don't need to support p2p connections at all, we just need to receive discovery packets (which is handled via UDP sockets in `NodeTable`). I'll take a closer look at how to avoid starting the TCP listener (or maybe we can create the `NodeTable `without going through `Host`, though I doubt it since I think the `NodeTable `depends on the host e.g. it uses a reference to `Host`'s boost IO service to listen for discovery packets)

I'm thinking of adding a boolean parameter to `NetworkConfig` named something like `p2p `which aleth-bootnode's `main `would set to `false`. In `Host `we would then skip starting the capability threads and the tcp4 acceptor in `Host::startedWorking`:

https://github.com/ethereum/aleth/blob/ec3886029393fc9927b130ba8f8671480d810391/libp2p/Host.cpp#L774-L787

We could also turn `Host::m_tcp4Acceptor` and `Host::m_ioService` into pointer types and only create them if `NetworkConfig::p2p` is `true`. 

I think we should still restore the data from `aleth-bootnode-network.rlp` since that can contain node table data.

@gumb0,@chfast: Thoughts?

**Comment by gumb0** [comment]
> I'm thinking of adding a boolean parameter to NetworkConfig named something like p2p which aleth-bootnode's main would set to false

Maybe flag is not needed - we can instead just look into `m_capabilities` - if it's empty (no capabilities registered), we can skip initializing devp2p stuff. This will give us the flexibility of adding capabilities and enabling devp2p at run time after network restart (which can be done through RPC)

> In Host we would then skip starting the capability threads and the tcp4 acceptor in Host::startedWorking:

Not starting the tcp acceptor will disable getting incoming connections from other nodes, but we should also not do this https://github.com/ethereum/aleth/blob/b92056768376d42b809e2a80afd3178b2dead29f/libp2p/Host.cpp#L377-L378
(starting the outgoing connections to nodes added through discovery)

> We could also turn Host::m_tcp4Acceptor and Host::m_ioService into pointer types and only create them if NetworkConfig::p2p is true.

`m_ioService` is needed by `NodeTable` anyway.

**Comment by gumb0** [comment]
> It runs with very low resources, but the memory usage is growing slightly over time. Check if we don't keep some data forever (like pending peers, evictions).

It might be that the node table is still being populated, I don't know how fast it can be filled (it's filled and shouldn't grow anymore when it has 255 * 16 = 4080 nodes)

**Comment by gumb0** [comment]
> Why not? Discovery only uses UDP, why do we need to accept incoming connections from nodes if we're running discovery only?

We don't.
I'm saying we neither need to start tcp acceptor, nor call `connect()` in the `onNodeTableEvent()` handler.

**Comment by halfalicious** [comment]
Item 1 and 3 were addressed by #5463 (we don't need to explicitly ignore hello messages since we have no way or receiving them when we aren't running a TCP listener).

**Comment by chfast** [comment]
Replaced by https://github.com/ethereum/aleth/issues/5475.
