### ISSUE TITLE
Some question need your help

### ISSUE THREAD

**Issue by otis01329** [ethereum/aleth#5417]
Hi,

I need to do some research using the program inside this github.
So I need some help from you, thanks.

1. 
What is the difference between main.cpp in these folders?
(aleth、aleth-bootnode、aleth-key、aleth-vm)

2.
The variant LegacyVM::interpretCases() appears in both files. 
(/libaleth-interpreter/VM.cpp)
(/libevm/LegacyVM.cpp)

What is the difference between the two?

Thank you for your reply.

Best Regards,
CS, Ke

**Comment by halfalicious** [comment]
Hi CS, Ke,

Thanks for your interest in Aleth! Regarding your first question:

> 
> What is the difference between main.cpp in these folders?
> (aleth、aleth-bootnode、aleth-key、aleth-vm)
> 

Each of these are different tools:
* **Aleth**: This is the Ethereum client which you can use to sync to the Ethereum blockchain 
* **Aleth-bootnode**: This is a tool which just runs the [devp2p node discovery protocol ](https://github.com/ethereum/devp2p/blob/master/discv4.md) i.e. it doesn't run the full devp2p protocol so no peer connections are supported. You can use it to set up your own bootnode which Ethereum clients can query to find out about other Ethereum clients.
* **Aleth-key:** I'm not familiar with this tool, but I looked at the `--help` output and it appears to be a command-line wallet. 
* **Aleth-vm**: I'm not familiar with this tool either, but I looked at the `--help` output and it appears to be a tool that you can use to execute simple txs on an Ethereum VM via the command line. @chfast  would know more since he's our resident VM expert 😃 

@chfast Should also be able to answer your other VM questions.

**Comment by halfalicious** [comment]
Please reactivate if you still have questions
