### ISSUE TITLE
Discovery: Node responses with different public key

### ISSUE THREAD

**Issue by chfast** [ethereum/aleth#5431]
It happens quite often that a pinged node can response with a pong but with different public key.

```
DEBUG 01-14 11:16:58 p2p  discov Ping to ##967b8992…@3.86.38.233 UDP 30303 TCP 30303
DEBUG 01-14 11:16:59 p2p  discov Pong from ##3d825603…@3.86.38.233:30303
DEBUG 01-14 11:16:59 p2p  discov Unexpected PONG from 3.86.38.233:30303
```

**Comment by halfalicious** [comment]
I wonder if the pinged node is an aleth node running on Windows...by default a Windows aleth node will generate a new pub/priv key pair on each launch since bug #5370  prevents it from saving its network config on shutdown.

**Comment by gumb0** [comment]
What we should do I think is map `EndpointPinged`->`NodeValidation` instead of `NodeID`->`NodeValidation` in `m_sentPings` (and add `NodeID` to `NodeValidation`)

Then Pong handler will have
```
if nodeId == oldNodeId
  // this part alredy exists
  update lastPongReceivedTime
  if validation has replacementNodeId
    dropNode(replacement) 
else
   addNode(nodeId, Known) // add it with current time as lastPongReceivedTime
```

This way in case NodeID changed the old one will be evicted by timeout and replaced in the node table with replacementNodeId
