### ISSUE TITLE
could someone correct the code much more normalization?

### ISSUE THREAD

**Issue by natahew** [ethereum/aleth#5493]
could someone correct the code much more normalization? such as the aleth project, the main method has   more than 1000 lines..., 
It's hell......

**Comment by halfalicious** [comment]
Thanks for filing this issue! Aleth (formerly cpp-ethereum) is one of the first Ethereum clients and was created as a proof-of-concept. As with any proof-of-concept-code, the focus was on creating a working implementation and not necessarily code readability / conciseness. While we've worked on refactoring the code over the years, we have limited resources so our focus is on adding new features and fixing bugs. If you find bugs or want new features, please file new issues. Otherwise, if you feel strongly that there are code readability problems that need to be addressed, you're welcome to fix them and open a PR. We always welcome contributions from others :smiley:  You can find our contributor and coding style guidelines here:
* **Contributor and review guidelines**: https://github.com/ethereum/aleth/blob/master/CONTRIBUTING.md
* **Coding style guidelines**: https://github.com/ethereum/aleth/blob/master/CODING_STYLE.md

Our Gitter channel is a good place for questions: https://gitter.im/ethereum/aleth

**Comment by natahew** [comment]
> Thanks for filing this issue! Aleth (formerly cpp-ethereum) is one of the first Ethereum clients and was created as a proof-of-concept. As with any proof-of-concept-code, the focus was on creating a working implementation and not necessarily code readability / conciseness. While we've worked on refactoring the code over the years, we have limited resources so our focus is on adding new features and fixing bugs. If you find bugs or want new features, please file new issues. Otherwise, if you feel strongly that there are code readability problems that need to be addressed, you're welcome to fix them and open a PR. We always welcome contributions from others 😃 You can find our contributor and coding style guidelines here:
> 
> * **Contributor and review guidelines**: https://github.com/ethereum/aleth/blob/master/CONTRIBUTING.md
> * **Coding style guidelines**: https://github.com/ethereum/aleth/blob/master/CODING_STYLE.md
> 
> Our Gitter channel is a good place for questions: https://gitter.im/ethereum/aleth

thank you,i‘ll try it
