### ISSUE TITLE
Build fails on Windows because yaml-cpp fails to build

### ISSUE THREAD

**Issue by damian123** [ethereum/aleth#5516]
I have an problem building aleth on Windows because yaml-cpp fails.

I ran this command:
`cmake .. -DCMAKE_GENERATOR_PLATFORM=x64
`
But I get an error in the hunter part 

C:\.hunter\_Base\c4cfcc0\1643554\402d68a\Build\yaml-cpp\Source\include\yaml-cpp/exceptions.h(208): **error C3646: '_NOEXCEPT': unknown override specifier** [C:\.hunter\_Base\c4cfcc0\1643554\402d68a\Build\yaml-cpp\Build\yaml-cpp-Release-prefix\src\yaml-cpp-Release-build\yaml-cpp.vcxproj] [C:\.hunter\_Base\c4cfcc0\1643554\402d68a\Build\yaml-cpp\Build\yaml-cpp-Release.vcxproj]

The complete output is [build.txt](https://github.com/ethereum/aleth/files/2944560/build.txt)

I am on Windows 10, Visual Studio 2017 and cmake 3.13.4

**Comment by halfalicious** [comment]
Can you try:

1. `cmake .. -G "Visual Studio 14 2015 Win64"`
2. `cmake --build . --config <Debug|RelWithDebInfo>`

**Comment by damian123** [comment]
`cmake .. -G "Visual Studio 14 2015 Win64"` fails because I have VS 2017 installed.
When I run `cmake .. -G "Visual Studio 15 2017 Win64"` I get the same error as above.

**Comment by chfast** [comment]
We also don't support Virtual Studio 2017 yet.

**Comment by Mag517** [comment]
Hello, I am just following up as to if a workaround is known for the use of VS2017. Thank you!

**Comment by halfalicious** [comment]
I believe this will be fixed by upgrading [Hunter to the latest version (v0.23.211)](https://github.com/ruslo/hunter/releases/tag/v0.23.211) ([archive link](https://github.com/ruslo/hunter/archive/v0.23.211.tar.gz)) - the reason that the dependencies fail to build when generating the VS 2017 solution is because YAML-CPP has a workaround for VS's lack of `noexcept `which uses a token that's no longer present on VS2017  >= 15.8 (`_NOEXCEPT`). This was fixed in YAML-CPP release 0.6.2-p1 ([fix commit](https://github.com/jbeder/yaml-cpp/commit/0f9a586ca1dc29c2ecb8dd715a315b93e3f40f79)), but the version of Hunter that Aleth currently uses ([0.23.178](https://github.com/jbeder/yaml-cpp/commit/0f9a586ca1dc29c2ecb8dd715a315b93e3f40f79)) only has YAML-CPP version 0.6.2-p0.
