### ISSUE TITLE
Remove --private option from aleth

### ISSUE THREAD

**Issue by halfalicious** [ethereum/aleth#5531]
Aleth's `--private` option is unnecessary and should be removed - it sets some chain parameters to certain values, but in order to use a private chain one must also specify a chain configuration json file (via the `--config` parameter) and this config file must also include values for those chain parameters.

The private option's usage is logged here: https://github.com/ethereum/aleth/blob/523c965e9db1c9a1f6dde7ff7a042c28f6e5f13c/aleth/main.cpp#L211

The private option is parsed here: https://github.com/ethereum/aleth/blob/ad6f54f662fc7ddeac8bfd2c115362675e4800db/aleth/main.cpp#L626-L635

Chain parameters are then set to certain values (based on whether or not `--private` was supplied) here: https://github.com/ethereum/aleth/blob/ad6f54f662fc7ddeac8bfd2c115362675e4800db/aleth/main.cpp#L698-L703

The chain configuration file is processed here: https://github.com/ethereum/aleth/blob/ad6f54f662fc7ddeac8bfd2c115362675e4800db/aleth/main.cpp#L681-L694

**Comment by twinstar26** [comment]
To resolve this issue,

I am planning to remove
https://github.com/ethereum/aleth/blob/523c965e9db1c9a1f6dde7ff7a042c28f6e5f13c/aleth/main.cpp#L211
so that "private" key-value pair is not created in map "vm".

Then I am going to move the contents of
https://github.com/ethereum/aleth/blob/523c965e9db1c9a1f6dde7ff7a042c28f6e5f13c/aleth/main.cpp#L626-L635
to
https://github.com/ethereum/aleth/blob/523c965e9db1c9a1f6dde7ff7a042c28f6e5f13c/aleth/main.cpp#L468-L486
with appropriate condition checking, but the string "privateChain" which used to contain the value of key "private" from map "vm" will now remain NULL. 
So is this information going to be included in "configJSON"? Or we can modify 
https://github.com/ethereum/aleth/blob/523c965e9db1c9a1f6dde7ff7a042c28f6e5f13c/aleth/main.cpp#L213
to "value<string>()->multitoken()" so as to obtain --config value as well as --private value (if it exists).

Please pardon my noviceness as this is my first open source issue.

**Comment by twinstar26** [comment]
@halfalicious

**Comment by halfalicious** [comment]
Thank you for your interest in fixing this issue @twinstar26 ! 

I don't think the multitoken change is needed - you should also remove the `privateChain` string definition and update the following places where it's checked accordingly:

https://github.com/ethereum/aleth/blob/32bb833e82133706713b0ed1ad397caafb8c8738/aleth/main.cpp#L759

and

https://github.com/ethereum/aleth/blob/32bb833e82133706713b0ed1ad397caafb8c8738/aleth/main.cpp#L1029

So after your changes, `--private` won't be recognized and one will have to explicitly disable discovery (`--no-discovery`) and/or disable attempting to peer with the official Ethereum bootnodes (`--no-bootstrap`) when they wish to run a private chain without discovery (i.e. manually add peers via `--peerset` or RPC).

Also, if you haven't already, please review the documentation for contributors: https://github.com/ethereum/aleth/blob/master/CONTRIBUTING.md

Let me know if you have any questions and thanks again! 😃

**Comment by twinstar26** [comment]
@halfalicious  thanks for the warmness...

I have created a pull request.
And I have a suggestion.

Suggestion 1: The definition of "enableDiscovery" is redundant throughout the repo. So should I remove it (considering any future use of that bool variable)??
https://github.com/ethereum/aleth/blob/32bb833e82133706713b0ed1ad397caafb8c8738/aleth/main.cpp#L152

**Comment by halfalicious** [comment]
> 
> 
> @halfalicious thanks for the warmness...
> 
> I have created a pull request.
> And I have a suggestion.
> 
> Suggestion 1: The definition of "enableDiscovery" is redundant throughout the repo. So should I remove it (considering any future use of that bool variable)??
> 
> [aleth/aleth/main.cpp](https://github.com/ethereum/aleth/blob/32bb833e82133706713b0ed1ad397caafb8c8738/aleth/main.cpp#L152)
> 
> Line 152 in [32bb833](/ethereum/aleth/commit/32bb833e82133706713b0ed1ad397caafb8c8738)
>  bool enableDiscovery = false;

Thank you for calling this out 😄  You're correct, this can be removed

**Comment by halfalicious** [comment]
@twinstar26 : Thanks for your contribution! 😄
